version: '3.8'
services:
  postgres-SQL-db:
    container_name: postgres-SQL-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local